name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend image
        run: |
          docker build -t sadekomrane/backend:latest ./backend
          docker push sadekomrane/backend:latest

      - name: Build and push frontend image
        run: |
          docker build -t sadekomrane/frontend:latest ./frontend
          docker push sadekomrane/frontend:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull sadekomrane/backend:latest
            docker pull sadekomrane/frontend:latest
            docker stop backend frontend || true
            docker rm backend frontend || true
            docker run -d --name backend -p 9000:9000 sadekomrane/backend:latest
            docker run -d --name frontend -p 80:80 sadekomrane/frontend:latest
